statuses:
  - name: "ci/circleci: build"
    description: "CircleCI build status"
  - name: "codecov/project"
    description: "Codecov coverage status"

statuses:
  - pending
  - success
  - failure
